repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
      - id: forbid-tabs
        exclude_types: [python, javascript, dtd, markdown, makefile, xml]
        exclude: binary|\.bin$
  - repo: git://github.com/kintoandar/pre-commit.git
    rev: v2.1.0
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    stages:
      - commit
      - push
    hooks:
      - id: detect-aws-credentials
      - id: detect-private-key
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 062f0b028ae65827e04f91c1e6738cfcbe9b337f # v1.0.6
    hooks:
      - id: shell-lint
  - repo: https://github.com/ansible/ansible-lint
    rev: 5fac056c45595896c973fbde871f01f6cb14d74c # v26.4.0
    hooks:
      - id: ansible-lint
  - repo: https://github.com/prettier/prettier
    rev: d7108a79ec745c04292aabf22c4c1adbd690b191 # 3.8.3
    hooks:
      - id: prettier
  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.13.0
    hooks:
      - id: markdownlint
